language: java
jdk:
  - openjdk8

script: "mvn cobertura:cobertura"

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: contas-backend

after_success:
  - bash <(curl -s https://codecov.io/bash)